version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:12.19

jobs:
  test:
    executor: nodejs
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm lint
      - run:
          name: Run Front-End Test and Coverage
          command: |
            pnpm test:coverage

workflows:
  test:
    jobs:
      - test

commands:
  checkout-and-install:
    description: Get the code and install dependencies.
    steps:
      - run:
          name: Install pnpm
          command: |
            curl -f https://get.pnpm.io/v6.js | sudo node - add --global pnpm@5
      - checkout
      # Edit this comment somehow in order to invalidate the CircleCI cache.
      # Since the contents of this file affect the cache key, editing only a
      # comment will invalidate the cache without changing the behavior.
      - restore_cache:
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
            "pnpm-lock.yaml" }}
      - run:
          name: Setup Dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
            "pnpm-lock.yaml" }}
          paths:
            - node_modules
